import { CryptographyModule } from "@/infra/cryptography/cryptography.module";
import { DatabaseModule } from "@/infra/database/database.module";
import { EnvModule } from "@/infra/env/env.module";
import { MailModule } from "@/infra/mail/mail.module";
import {
	SignUpService,
	SignInService,
	GetCurrentUserService,
	UpdateUserService,
	DeleteUserService,
	SetupEmergencyPassphraseService,
	ForgotPasswordService,
	ResetPasswordWithPassphraseService,
	ResetPasswordWithTokenService,
	CreateCredentialService,
	ListCredentialsService,
	GetCredentialDetailService,
	EditCredentialDetailService,
	CreateCategoryService,
	UpdateCategoryService,
	FindAllCategoriesService,
	DeleteCategoryService,
	DeleteCredentialService,
	GetCategoryDetailsService,
	SetAutoLockTimeoutService,
} from "@/infra/services/services";
import { Module } from "@nestjs/common";

@Module({
	providers: [
		SignUpService,
		SignInService,
		GetCurrentUserService,
		UpdateUserService,
		DeleteUserService,
		SetupEmergencyPassphraseService,
		ForgotPasswordService,
		ResetPasswordWithPassphraseService,
		ResetPasswordWithTokenService,
		CreateCredentialService,
		ListCredentialsService,
		GetCredentialDetailService,
		EditCredentialDetailService,
		CreateCategoryService,
		UpdateCategoryService,
		FindAllCategoriesService,
		DeleteCategoryService,
		DeleteCredentialService,
		GetCategoryDetailsService,
		SetAutoLockTimeoutService,
	],
	exports: [
		SignUpService,
		SignInService,
		GetCurrentUserService,
		UpdateUserService,
		DeleteUserService,
		SetupEmergencyPassphraseService,
		ForgotPasswordService,
		ResetPasswordWithPassphraseService,
		ResetPasswordWithTokenService,
		CreateCredentialService,
		ListCredentialsService,
		GetCredentialDetailService,
		EditCredentialDetailService,
		CreateCategoryService,
		UpdateCategoryService,
		FindAllCategoriesService,
		DeleteCategoryService,
		DeleteCredentialService,
		GetCategoryDetailsService,
		SetAutoLockTimeoutService,
	],
	imports: [DatabaseModule, CryptographyModule, EnvModule, MailModule],
})
export class ServiceModule {}
