POST http://localhost:3333/auth/sign-up
HTTP/1.1 200 OK
Content-Type: application/json

{ 
  "email": "egnima.fototeste@enigma.com", 
  "password": "SenhaForte123@"
}

### Sign in
POST http://localhost:3333/auth/sign-in
HTTP/1.1 200 OK
Content-Type: application/json

{ 
  "email": "egnima.fototeste@enigma.com",
  "password": "SenhaForte123@"
}

### Forgot password 
POST http://localhost:3333/auth/forgot-password
HTTP/1.1 200 OK
Content-Type: application/json

{ 
  "email": "egnima.fototeste@enigma.com"
}

### Reset with emergency passphrase 

POST http://localhost:3333/auth/reset-password/passphrase
HTTP/1.1 200 OK
Content-Type: application/json

{ 
  "email": "egnima.teste@enigma.com", 
  "newPassword": "Senha-forte-123@@",
  "passphrase": "my-very-strong-passphrase"
}

### Reset with token

POST http://localhost:3333/auth/reset-password/verify-token
HTTP/1.1 200 OK
Content-Type: application/json

{ 
  "newPassword": "SenhaMudada123@@",
  "token": "faab1ac91d5db1cb7cdb16e38290075942625cb6d555c4b0188459b5d7dbdaaf"
}
