POST http://localhost:3333/auth/sign-up
HTTP/1.1 200 OK
Content-Type: application/json

{ 
  "email": "1234", 
  "password": "123456"
}

### Sign in
POST http://localhost:3333/auth/sign-in
HTTP/1.1 200 OK
Content-Type: application/json

{ 
  "email": "1234", 
  "password": "123456"
}
