@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YzRiNGM4Mi1lZTgxLTQ1YTAtODEzNS0zYzBlYzQxOTU3MjgiLCJpYXQiOjE3NjQxMjExMTYsImV4cCI6MTc2NDEyNDcxNn0.tPo3LOPAFzKJ9nDurGpmvjCYVJQUkc679WjO9K4VFkl_9CXQvFueTwK07QcaA1H1mwOOOFDycInpt8CKVgdHIz6aqK-ofjDH2uMYSsgWJ0x0M-tRAhfRy-1oBhpNpBw1QDskEJ8QPAwKjKCILwRVMMtWsDtkb0pD5c-eHXL_X34y17_1-THDhG3Z8Tp5ERXW2sP8toVTygB7z0jfe5VG9so1ntD5GJE3QT1kdy8S0EbQd6FDZouk1ps_WSh6etI0RhV_ECF20q5qPZPbU5_Xb1yxjjsVCe9XMuM6xuYihUP5IfQs3cYgJWUhTubFwIBVWGHcuUepLQpr5EZh_4Cw1A


### Create credential
POST http://localhost:3333/category/create
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "name": "Benana"
}

### List credential
GET http://localhost:3333/category/list
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get credential
GET http://localhost:3333/category/details/fac031ba-ea37-419b-bd76-8cc9150cea27
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Edit credential
PUT http://localhost:3333/category/edit/26e823a6-177b-40a1-8235-6e7fb88c4e90
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Banana"
}

### Delete credential
DELETE http://localhost:3333/category/delete/26e823a6-177b-40a1-8235-6e7fb88c4e90
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

