@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YTBlMzUxNC0yMjYzLTQ4ZmYtYmM0MS1iMTY4NjE2YTE5ZmQiLCJpYXQiOjE3NTg4MTUyNTMsImV4cCI6MTc1ODgxODg1M30.vIUz_uMgjy2K4pECfSVfj5Y3koBhIPd7NiyNJTUUji3bKn3e1Q23MtUiI8ved-wDPV13az38N4OuPViOKd09b8haxi8eanUgyeYDO2j03VXTM7Ejo9rVmUwtl_xTyK-FYl9S8x2nSixHkFyni5i4D_bgjPcWSxRqDhweSnGZkxy0GOWo-shxe5ht77p5shTzw9RX6jF7mt6ZNIonoNKGPXurLoDjcGPx1riBBiX_DUfUzGEGm4gjfpfi8GQv5T-vjaaXDRK1o-bjMcp8xBPrEBj_17nPcOZlCHFtxYcvhikKYkEhMoJBKQ9Uq6OooVhDP1KLMy2M7Q0aoUEy2viR4g


### Create credential
POST http://localhost:3333/category/create
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "name": "Benana"
}

### List credential
GET http://localhost:3333/category/list
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get credential
GET http://localhost:3333/category/details/e2ff33ac-bf11-4e41-a474-4e9434761171
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Edit credential
PUT http://localhost:3333/category/edit/26e823a6-177b-40a1-8235-6e7fb88c4e90
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Banana"
}

### Delete credential
DELETE http://localhost:3333/category/delete/26e823a6-177b-40a1-8235-6e7fb88c4e90
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

