@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNjQyNWVhZS1lZTk5LTQzYzQtODQ4OC1mZjY0MTk2NjAwMmUiLCJpYXQiOjE3NTk4NDkyNDAsImV4cCI6MTc1OTg1Mjg0MH0.EBgrOaf_-vsf55aI2lbkLDCvfcKxrz4AKMTOqqfuvVXJgMqV92lhDBXU1gQ_jdX60GfFW6Uj6dqfdiJMtHl4lOm-gN1R7I-FUUI6wT4AcYhZndDN_9_owXfZYrLetnssnlsNh8MSHL_Tf5I5JOVfnXuPUbukL18TRDYcMkmiPOf2DX_B546h2GiqsZ1bdKToYZoqIFbnTaB2rLbG9_100THWb4Fficfl9JseQSE1xUj9jlnsHGbG424oqRydDb4S3F8CTcLmmhAHw_LR4nXixv0HuP5BTnvUZNESJip8AOu8OoV0SLHYuTl5Sa3IaymN8d14To-f80Kg7_AxkrTSgA


### Create credential
POST http://localhost:3333/credentials/create
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "title": "Epic emergenca", 
  "username": "burnout", 
  "password": "123",
  "isEmergency": true
}
### List credentials
GET http://localhost:3333/credentials/list
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get credentail details
GET http://localhost:3333/credentials/details/92df3881-c946-46e4-85c3-609ce739f559
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Update credentail details
PUT http://localhost:3333/credentials/edit/92df3881-c946-46e4-85c3-609ce739f559
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "url": "Paozinho lindo",
  "categoryId": "362e3c52-af68-4d49-9459-b5b98cbaacd9"
}

### delete credentail details
DELETE http://localhost:3333/credentials/delete/97bc2e41-6878-4961-b9f0-8211c7cb2277
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
