@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YTBlMzUxNC0yMjYzLTQ4ZmYtYmM0MS1iMTY4NjE2YTE5ZmQiLCJpYXQiOjE3NTg4MDc2ODQsImV4cCI6MTc1ODgxMTI4NH0.Ai2tk7u6i6uRaE5DaRPgz_eyHFhLXvIdGoEnjU_l51EIvKuBYhvG5hCv-3icsYlt2YkeUxIGkpjgT8S7c0z-tiTrRFJYpXBZdzP0Di-iIIe6kndYIEIez7b01tqCDCuLwfSDCbj3lAgWdEATUNeurTO1Z4dVYNCl3bEiDc7SwOFicDlpLJeK--yzlAby0th7U0pd97a867VO27CeTFoSANT9KhsffoOrAIJk13uJKs7JKXs4gGz2bOHrlGkhjRshyjiIyDLSJkufv1ePYMyrIY2CgQIxj9HggFZaSyAQQXcAf2i8J1Y8aKPfzBJbsrl-j9G0YsPrqB4w5ocOW64hzA


### Create credential
POST http://localhost:3333/credentials/create
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "title": "Discord", 
  "username": "burnout", 
  "password": "123"
}
### List credentials
GET http://localhost:3333/credentials/list
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get credentail details
GET http://localhost:3333/credentials/details/97bc2e41-6878-4961-b9f0-8211c7cb2277
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Update credentail details
PUT http://localhost:3333/credentials/edit/9b44651c-1ab6-4e02-ade4-24eabc859780
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "url": "Paozinho lindo",
  "categoryId": "362e3c52-af68-4d49-9459-b5b98cbaacd9"
}

### delete credentail details
DELETE http://localhost:3333/credentials/delete/97bc2e41-6878-4961-b9f0-8211c7cb2277
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
