@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YTBlMzUxNC0yMjYzLTQ4ZmYtYmM0MS1iMTY4NjE2YTE5ZmQiLCJpYXQiOjE3NTg2Mjc5NjEsImV4cCI6MTc1ODYzMTU2MX0.EE3L9gXXdXP1_3BDxqqWGw82XPt9G1PrvxIDUzgAt-AJbjM9NxBE0K7vxRd1oXbhy6jKfM4HGFDDR8zDbWBTqzHvJyQIPWcPT8OdvAzjEcKjZVPN1jBhWmEOkV8ohYn9jHRwPDUb1ADJxAZTOL-Af01ZYn1F35NTlSV5K_mR4pMwxA8eaoY8FiSsev_Ilob4844Zxjd82EDg0PgFXZKSJpjQ5ak4viTRA7wrIiG_1q3_8XcUEC3_EqqzPWR_ZkrlTV91VnWh2CGWTWe5KwwButYsQ1KgEKqFS4aD4H7nMxE8kwUGWp2-6kw-uQtqfA7si2bJ-J066X3f6Sfp26p2KA


### Create credential
POST http://localhost:3333/credentials/create
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "title": "Discord", 
  "username": "burnout", 
  "password": "paozinho123"
}
### List credentials
GET http://localhost:3333/credentials/list
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get credentail details
GET http://localhost:3333/credentials/details/97bc2e41-6878-4961-b9f0-8211c7cb2277
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Update credentail details
PUT http://localhost:3333/credentials/edit/9b44651c-1ab6-4e02-ade4-24eabc859780
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "url": "Paozinho lindo",
  "categoryId": "362e3c52-af68-4d49-9459-b5b98cbaacd9"
}

### delete credentail details
DELETE http://localhost:3333/credentials/delete/97bc2e41-6878-4961-b9f0-8211c7cb2277
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
