@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNzc1MzNmYy00OWRjLTRkYTktYTY0ZC00YjIwNmZhNGIzOTAiLCJpYXQiOjE3NjIxNzYyNDQsImV4cCI6MTc2MjE3OTg0NH0.ktoZcdpU6lq5oVSl9yNNo7oRi17MNey0YpNYpeLgWW0WeLqnQ_94ts5ctlh_fmEs1XZpFcpMYRNxW1-I24y7uKs8KTd5T3l5bgPAnYX1DuIen5mW9SCxpDRxG-Vg9LP_1tZkfOwW3k-dWav5ya7deik672mL90kTLtOE-gHeZhH7xQ51LqZnr5MfGZ_Mkp4-BQasuGOQCjgreLIqXrL7XkOFOBn7JHVbKfcIfJvFvWggXJw2AgHrYSchRnovp5qT9mj0ReLPdpueIogIWuZgv0tWANawxy7xaZY1w_5OIRFp12y8CKBiyfnpYSNkng-SrgR-V4NvaEpI9iY521jKMQ


### Create credential
POST http://localhost:3333/emergency-vault/list
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "emergencyVaultPassword": "SenhaCofre123@"
}
