@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNzc1MzNmYy00OWRjLTRkYTktYTY0ZC00YjIwNmZhNGIzOTAiLCJpYXQiOjE3NjIyNTIyNTksImV4cCI6MTc2MjI1NTg1OX0.danV8J4PyG81xOE2sjOrdshs-vziD-xWRqivjXegzpcb5MjUCe03DAm_7jXXJHbhw-1437_gEpEpVsKYJZWhDjxaKGLhjR-PYtZ7VIICi_dh-Fdmv7DxGXbztkb9cvzS37kkT1yuWc62wvrk8C1qtCBcPKMeM1vd_bQXo2T2UdAixh1z0Fn5kfZvn8SPug0fd82LfLc6aExU_fLzTNLmevnxcZWoJ89_kAf8j514zMlo4MnuvvFyTzi2YecsTYd3YWTXVnZMX0gTdBcadmlR69iYyyOEvfJxu6VK8Tl9gSTUOKZwN01PxgkVA9ctDOpXBLLXhMjQxRF5XQ4bAVCRkw


## Get report
GET http://localhost:3333/report/vault-health
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
