@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNzc1MzNmYy00OWRjLTRkYTktYTY0ZC00YjIwNmZhNGIzOTAiLCJpYXQiOjE3NjIyNjY4MDIsImV4cCI6MTc2MjI3MDQwMn0.LQ_tuncO7NINwWWnyN5SwqDLuMdBc_Dga0lNUPMpW_MpkMdC1b9JsErXl1oOcvgQlf6Y11Q3UqxuBpfgvhTaNpPibL-sMltk6FJuMNk1cOJJese3eJfAqjiPt5LBQ7d_Js3lOr9_OWZlCW89GcVLOdVDfMHap2NzA6t_B-z_02pTe2bgyH3fDvKzLMS4wioddB69XV6-qIN_4Nw1wgRj-hVVIOiaLLzYYEyIaTCLFR9SGbuIbH27OHlPTyLpmif7rUQgVHiozSfV40WftsxlxKbEGNBqGsxWqkhkQyvCb0PaABRIEBuT9qqa0_3NPi1F1GzmtdPNVlFUPit8DHruIg


## Get report
GET http://localhost:3333/report/vault-health
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get report
GET http://localhost:3333/report/vault-health/pdf
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
