@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNzc1MzNmYy00OWRjLTRkYTktYTY0ZC00YjIwNmZhNGIzOTAiLCJpYXQiOjE3NjI0NzMyNTcsImV4cCI6MTc2MjQ3Njg1N30.I3U4Ft89RBaZR4YPY-bw1njx3_o3XIQ0gbeadJWjBHhIFxlDL_7r9bZa5-PcOC42bhBjb4S4ePHm-hlPdse0YG2MUIyUFUst7P4Zeg9NjJ6lKxNVrf0eGLSZGta2WYZd0zHVLB3Ob2DXExYaTUBfFxCy8m4N9uw6Qyq_zTTzV0HAXOz_Ku56nC6KnFwAOmwnsmw91PsKJa5XoeztjA3WNFIPndl_4cWJHNVTs1IaV4ilip-8qq4UIMpvyFAJaoRw5lwBomT3cxWb7v14hKP9YF-ESaAJfYSxMsB6qgjotWLoQ1qIzv5lIsphdoxso2cjJknAz6YDnRpDT764YrsnKA


### Create note
POST http://localhost:3333/safe-note/create
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "title": "Nota longa", 
  "content": "nota 4783907489374893271849037214893748932798",
  "isEmergency": true
}
### List credentials
GET http://localhost:3333/safe-note/list
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get credentail details
GET http://localhost:3333/safe-note/details/1b9277aa-b133-40e2-9a46-910eadcf8965
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Update credentail details
PUT http://localhost:3333/safe-note/edit/fd4b7a99-40e4-415c-9d4b-1ff828ddccd3
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "title": "Eae"
}

### delete credentail details
DELETE http://localhost:3333/safe-note/delete/d0641ccf-f9d9-4f09-8467-48791a2dc2f9
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
