@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNjQyNWVhZS1lZTk5LTQzYzQtODQ4OC1mZjY0MTk2NjAwMmUiLCJpYXQiOjE3NjA5MTQ3NjIsImV4cCI6MTc2MDkxODM2Mn0.rHzkzj7GTXGbG-Zn7Uu3Zd4CGMFVp2fq_qcadv64EToVyurIU-TNQIukdQt1CNQ-NP54Tow8eVcuwK8VuumxhpcA39sckIte4PZI1isSFzq0HnnsDcIJaX5PT0b9h3B74fVIx-P-QSwGUvykDMkbHvD8D2mxBrlxSeVjb-_SU6w3GZeinh1RtJQuqWzCTvQkkWHOJpyHWCEuyP4YVVbtTgaHQwMFPR8-2pGC79NofEZSyxrdCJ-gM4oraRjJ09Z7RpDWTdFIucagvTCWcyr1M-jiHkxWGpGh_OidoRWEAuRYpm1Con12Vvw69GQ5VGwKdgltaJ_o-mCCwNaEf2tm0w


### Create note
POST http://localhost:3333/safe-note/create
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "title": "Nota emertencia", 
  "content": "nota segura",
  "isEmergency": true
}
### List credentials
GET http://localhost:3333/safe-note/list
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get credentail details
GET http://localhost:3333/safe-note/details/fd4b7a99-40e4-415c-9d4b-1ff828ddccd3
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Update credentail details
PUT http://localhost:3333/safe-note/edit/fd4b7a99-40e4-415c-9d4b-1ff828ddccd3
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "title": "Eae"
}

### delete credentail details
DELETE http://localhost:3333/safe-note/delete/fd4b7a99-40e4-415c-9d4b-1ff828ddccd3
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
