@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNzc1MzNmYy00OWRjLTRkYTktYTY0ZC00YjIwNmZhNGIzOTAiLCJpYXQiOjE3NjIxNzY5MTQsImV4cCI6MTc2MjE4MDUxNH0.yBMrduPLZ8JlA6GORInzOgbb75_y17l4Ra7UYvqTXzogvIiZKOVEgyBoYd9QDX5wR0lnv1wgU9LxCRzdYN8TvTmVxFc-6FpWyt1FtsbHxIIiUyhQVThl_dTHoq22dIo9f3HxUTas4X4cQ4A61xZdo2eZIZmLEiUJ9O0Vl3Anu6ghDmLsYSWafd8cqkz8SzENUhG3Twozf9sUlCOlbkDcwhOuWRCL5_zaKVRxazdNL7U5zuTTHBkZP3u6XLlbCv5J2bLNunB36T5vKsoEWB-YNJBrKgfhQpvtJQagDrhRAVfFyX625xYP048GkY5Y0wfRLIij1c2C8ubHezwLAdRRnA


### Create note
POST http://localhost:3333/safe-note/create
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "title": "Nota longa", 
  "content": "nota 4783907489374893271849037214893748932798",
  "isEmergency": true
}
### List credentials
GET http://localhost:3333/safe-note/list
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get credentail details
GET http://localhost:3333/safe-note/details/1b9277aa-b133-40e2-9a46-910eadcf8965
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Update credentail details
PUT http://localhost:3333/safe-note/edit/fd4b7a99-40e4-415c-9d4b-1ff828ddccd3
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "title": "Eae"
}

### delete credentail details
DELETE http://localhost:3333/safe-note/delete/d0641ccf-f9d9-4f09-8467-48791a2dc2f9
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
