@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNGYyODBiMC0yZTUxLTQ0ZWQtYmNiNy01MDY0ZGQ1ODg2MTAiLCJpYXQiOjE3NTYzNzYwOTgsImV4cCI6MTc1NjM3OTY5OH0.d3UkSb7yaFC36gnnWeqsTcuL3IzpCum-IBOEe27QF3TKnEAQpxobLCg1txrF5-jzyxhCLtGUfE-8yogHFJqFyJLV7BrqwDavMEADgX4-0iO09im9AQTz5WbhBvU_ptkLwDFLwWeNe5Y4H_9igIqJpAJGy21LiLPeU_TmwdbF71_L9kJCYuBxpPtMRWXcUn0ZXhmX8H8JYf72HlIlTHTXWEdItTu9NIFj6sfZEpf5vgcVMBTuqgpuBRNYFZM3lWpIQphbqofoSsgUWOsIAVQTaJlRgV1R7g5y46s8mmIYf4TQZVNQDXAVZCya9CB5-XaciPiqKafEbCzXrNQtMn1Opg


POST http://localhost:3333/security/setup-emergency-passphrase
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
   "passphrase": "my-very-strong-passphrase",
   "password": "123456"
}

### Nothing
