@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNjQyNWVhZS1lZTk5LTQzYzQtODQ4OC1mZjY0MTk2NjAwMmUiLCJpYXQiOjE3NjE5MTY0NzIsImV4cCI6MTc2MTkyMDA3Mn0.vROoXhsifjHoD0DuotNqhKNWpfdcJhKweMNvlKvfmr_7GEBjqYMT1Ys3sZ_SFtTtO3xdOF5TMdC_WCkOnmTS4v8sUZpOruutL2gLMoIcxDEbLOiWvKzg6Coe2digGpwUr0zCClpnrCP8Fc91BySVv8eexmPf2s32V1N8uasdEgWS2tDLhUDJbrLXS8_R-SwK66VBItuHUs-Su8rU4GeTV9hQ8ajxa8TWjxOySK21pSzOVFYhN5z8P94ICyIDat3sMXP2HnyExe0Uz1v87db7Ki7VxDCgep_e1k7NjIaHokQlrHsuwsk2nxA2hG9_mMM3FKo_8H5Q9txOlv6yR7N_Bw


POST http://localhost:3333/security/setup-emergency-passphrase
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
   "passphrase": "my-very-strong-passphrase",
   "password": "SenhaForte123@"
}

### Nothing

POST http://localhost:3333/security/set-autolock-timeout
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
   "autoLockTimeoutMinutes": 30
}
### vault

POST http://localhost:3333/security/setup-emergency-vault
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
   "emergencyVaultPassword": "SenhaCofre123@",
   "password": "SenhaForte123@"
}
