
@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNzc1MzNmYy00OWRjLTRkYTktYTY0ZC00YjIwNmZhNGIzOTAiLCJpYXQiOjE3NjIyNTIyNTksImV4cCI6MTc2MjI1NTg1OX0.danV8J4PyG81xOE2sjOrdshs-vziD-xWRqivjXegzpcb5MjUCe03DAm_7jXXJHbhw-1437_gEpEpVsKYJZWhDjxaKGLhjR-PYtZ7VIICi_dh-Fdmv7DxGXbztkb9cvzS37kkT1yuWc62wvrk8C1qtCBcPKMeM1vd_bQXo2T2UdAixh1z0Fn5kfZvn8SPug0fd82LfLc6aExU_fLzTNLmevnxcZWoJ89_kAf8j514zMlo4MnuvvFyTzi2YecsTYd3YWTXVnZMX0gTdBcadmlR69iYyyOEvfJxu6VK8Tl9gSTUOKZwN01PxgkVA9ctDOpXBLLXhMjQxRF5XQ4bAVCRkw


### Create share
POST http://localhost:3333/share/create
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "credentialId": "f2a84d65-6625-4e39-ba6a-2445390662b4",
  "masterPassword": "SenhaForte123@",
  "expiresIn": "7d",
  "deleteOnRead": false
}

### Get shared item
GET http://localhost:3333/share/3aa4477d-3457-43d7-b3b1-964406ab303a#222f41a37e7d91bf8e746a55728f54f716fc1b6014f52c60b4679fc842789136
HTTP/1.1 201 Created
Content-Type: application/json

### delete shared item
DELETE  http://localhost:3333/share/3aa4477d-3457-43d7-b3b1-964406ab303a#222f41a37e7d91bf8e746a55728f54f716fc1b6014f52c60b4679fc842789136
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get all my shared items
GET  http://localhost:3333/share
HTTP/1.1 201 Created
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
