@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjN2I3ZDlmOS03ZGI2LTQ2MGItOGMyMC03NGFjNTdiMzJhMWUiLCJpYXQiOjE3NTYzOTQ0OTUsImV4cCI6MTc1NjM5ODA5NX0.WfJeyX4Bs1SVkJqTtWLG-RB0OSTzj0-DSlCSa-_zI-RtxfH0dBquq4yoMvMVTgOXHgSg_3GCjZn5A2NMXN4McUmokOdS5OJbQPxXcPxkzQ08d8GNUi-wtpgKAUFLo_0gcdjmUig-6E8qX2dZlCtuZZCo99FUzCSJohQ_K2pbKbsxzQId51nOxEdydNDe8IQPfBe3YeyAzJErs-GKmQV0QKxOr41r_v2F7HrY3FsJQlWPZzCAGGjvL-7uCbMzb6SAu6mUpmN_HedMcKeOEWuuc4uX-PbZ2fZJ-uR7vKNg4xsM1MARgTfl1Gb4wlB4Ymu-MwbbAeepFSMufFW1gvFY5Q


### Get current user
GET http://localhost:3333/users/me
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


### Update user
PUT http://localhost:3333/users/update/073915ec-bbc6-4b25-9586-2d3b7db5eb58
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "email": "email@email.com", 
  "password": "123456"
}
### Delete user
DELETE http://localhost:3333/users/delete/073915ec-bbc6-4b25-9586-2d3b7db5eb58
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "email": "email@email.com", 
  "password": "123456"
}
