@TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYTU2YWQ1NS0wMjZkLTRjNmYtODJkYi01MDVkZThmNGEzNWMiLCJpYXQiOjE3NTg5OTExOTUsImV4cCI6MTc1ODk5NDc5NX0.VlE82EZUx_F_ElHAUp41bLS1gn9pF1yQJjowP2alOhzcKndH71sieKbQhZzH1OyWu93fS-PEjl2E_SRyRbQvLMRHaXKgYZot1NqKWblN9XwKmTi6UCRZqmQpd-oVFP6veMNtqM0E9i6iA6w5WZbA5-5tebjRk1f08aIZ7RqfuT_VSA9jjkJBN5Fj-hhNh43OqOwGSepAQrbjcVuqN1Bq4c_jOpqkKiki3PlIO6wQRioY1-_Tpu19JTtZXiCG4j1eSeUhuEzYgWc9mb1FNZSUIuSAA5vlNE2bNwkj_V6yDE6jGxTR0mnkwkdVM-zNzKBip0GoVliNYj9cksC9cCUgQA


### Get current user
GET http://localhost:3333/users/me
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


### Update user
PUT http://localhost:3333/users/update
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "email": "email@email.com", 
  "password": "123456"
}
### Delete user
DELETE http://localhost:3333/users/delete
HTTP/1.1 200 OK
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "email": "email@email.com", 
  "password": "123456"
}
